version: '3.9'

services:

  # defining the name of the service
  kong:

    # defining the image we want to use as base
    image: kong:3.1.1-alpine
    
    # defingin container name
    container_name: kong

    # implementing the config for db less configs
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml

    # declaring the environment variables 
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001

    # outer ports
    ports:
      - "80:8000"
      - "8001:8001"
  
  postgres-db:
    container_name: postgres-db
    image: postgres:15-alpine
    volumes:
      - ./postgre/data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


    restart: always

  todo_api:
    build: 
      context: ./services/todo-api
      dockerfile: ./Dockerfile
    container_name: todo_api
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./services/todo-api/main.py:/user/src/main.py
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db/postgres
    depends_on:
      - postgres-db
    restart: on-failure

  todo_grpc:
    container_name: todo_grpc
    build: 
      context: ./services/todo-grpc
      dockerfile: ./Dockerfile
    expose:
      - 50051
    command: sh -c "python main.py"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db/postgres
    depends_on:
      - postgres-db
    restart: on-failure



